List<String> expectedStudentsList = [
  '1-100',
  '100-300',
  '300-500',
  '500-1000',
  '1000 - .......',
];
List<Map<String,dynamic>> governorates = [
  {'governorate':'Cairo','code':'01'},
  {'governorate':'Alexandria','code':'02'},
  {'governorate':'PortSaid','code':'03'},
  {'governorate':'Suez','code':'04'},
  {'governorate':'damietta','code':'11'},
  {'governorate':'Dakahlia','code':'12'},
  {'governorate':'Sharqia','code':'13'},
  {'governorate':'Qalyubia','code':'14'},
  {'governorate':'Kafr El Sheikh','code':'15'},
  {'governorate':'Gharbia','code':'16'},
  {'governorate':'Monufia','code':'17'},
  {'governorate':'Beheira','code':'18'},
  {'governorate':'Ismailia','code':'19'},
  {'governorate':'Giza','code':'21'},
  {'governorate':'Beni Suef','code':'22'},
  {'governorate':'Faiyum','code':'23'},
  {'governorate':'Minya','code':'24'},
  {'governorate':'Asyut','code':'25'},
  {'governorate':'Sohag','code':'26'},
  {'governorate':'Qena','code':'27'},
  {'governorate':'Aswan','code':'28'},
  {'governorate':'Luxor','code':'29'},
  {'governorate':'Red Sea','code':'31'},
  {'governorate':'New Valley','code':'32'},
  {'governorate':'Matruh','code':'33'},
  {'governorate':'North Sinai','code':'34'},
  {'governorate':'South Sinai','code':'35'},
];


List<String>arabicSubjects=[
  "لغة عربية",
  "رياضيات",
  "علوم",
  "دراسات",
  "إنجليزي",
  "الماني",
  "لغة فرنسية",
  "احياء",
  "جغرافيا",
  "تاريخ",
  "كيمياء",
  "فيزياء",
  "جيولوجيا",
  "علم نفس",
  "فلسفة",
  "احصاء",
];

List<String>englishSubjects=[
  "Arabic",
  "Math",
  'Science',
  "Studies",
  "English",
  "German",
  "French",
  "Biology",
  "geography",
  "History",
  "Chemistry",
  "Physics",
  "geology",
  "Psychology",
  "philosophy",
  "statistic",
];

List<String>frenchSubjects=[
  "arabe",
  "mathématiques",
  "Science",
  "Études",
  "Anglais",
  "allemande",
  "française",
  "Biolog",
  "géographie",
  "Histoire",
  "Chimie",
  "Physique",
  "géologie",
  "Psychologie",
  "philosophie",
  "Compter",
];
